<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup>
        <PackageId>OpBlazorUI.Base</PackageId>
        <Version>1.0.0</Version>
        <Authors>OpenNG</Authors>
        <Company>OpenNG</Company>
        <Description>Optimus UI components for Blazor.</Description>
        <PackageTags>blazor;optimus-ui;components;ui;openng</PackageTags>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageProjectUrl>https://github.com/victorAFRodrigues/OpBlazorUI</PackageProjectUrl>
        <RepositoryUrl>https://github.com/victorAFRodrigues/OpBlazorUI</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
    </PropertyGroup>


    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.9"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="../../../README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
